#include "SurvivalAutoPlayerTestSettings.h"

USurvivalAutoPlayerTestSettings::USurvivalAutoPlayerTestSettings() {
    this->bUseFixedRandomSeed = false;
    this->FixedRandomSeed = 0;
    this->bUsedFixedPlaythroughID = false;
    this->DeltaTimeCap = 1.00f;
    this->bDisableTimeCapIfLowFramerate = true;
    this->DisableTimeCapFrameCount = 5;
    this->TestLevels.AddDefaulted(2);
    this->bEnableTraveling = true;
    this->MinTravelTime = 300.00f;
    this->MaxTravelTime = 1200.00f;
    this->bAllowTravelingToCurrentMap = false;
    this->bCanReturnToMainMenu = false;
    this->ChanceToReturnToMenu = 0.50f;
    this->MainMenuSoakTime = 90.00f;
    this->bEnableQuickSave = false;
    this->bEnableQuickSaveLoad = true;
    this->bOnlyLoadQuickSavesMadeOnCurrentMap = false;
    this->MinQuickSaveWaitTime = 30.00f;
    this->MaxQuickSaveWaitTime = 60.00f;
    this->MinQuickLoadWaitTime = 150.00f;
    this->MaxQuickLoadWaitTime = 250.00f;
    this->bGhost = false;
    this->bEnableRandomPathing = true;
    this->PathingNewLocationRadius = 30000.00f;
    this->PathingNewLocationHeightVariance = 2500.00f;
    this->bFaceAlongPath = true;
    this->bTeleportIfStuckPathing = true;
    this->PathingStuckTeleportRadius = 5000.00f;
    this->PathingVisitedTileSize = 400.00f;
    this->PathingGoalProjectionExtents = 300.00f;
    this->PathingVisitingRadius = 600.00f;
    this->bAllowControlRotationSnapping = true;
    this->MinSnapRotationWaitTime = 30.00f;
    this->MaxSnapRotationWaitTime = 60.00f;
    this->MinSnapRotationAmount = 45.00f;
    this->MaxSnapRotationAmount = 90.00f;
    this->bEnableTeleporting = true;
    this->bTeleportPlaceOnGround = true;
    this->TeleportHeight = 35000.00f;
    this->TeleportNewLocationDistance = 10000.00f;
    this->MinTeleportWaitTime = 30.00f;
    this->MaxTeleportWaitTime = 60.00f;
    this->bGodMode = true;
    this->bResurrect = true;
    this->bAttackAI = true;
    this->MaximumAttackDistance = 10000.00f;
    this->bOnlyAttackEnemies = true;
    this->MinAttackWaitTime = 0.25f;
    this->MaxAttackWaitTime = 1.50f;
    this->bEnableWeaponSwapping = true;
    this->MinWeaponSwapWaitTime = 30.00f;
    this->MaxWeaponSwapWaitTime = 60.00f;
    this->bEnableArmorSwapping = true;
    this->MinArmorSwapWaitTime = 30.00f;
    this->MaxArmorSwapWaitTime = 60.00f;
    this->bEnableScreenshots = true;
    this->ScreenshotRate = 60.00f;
    this->NumberOfScreenshotsToKeep = 15;
    this->bEnableMemoryInfoLogging = true;
    this->MemoryInfoLogRate = 120.00f;
    this->bLogMemoryInfoOnMapLoad = true;
    this->bConsoleCommandsEnabled = true;
    this->ConsoleCommandProperties.AddDefaulted(5);
    this->bInfoTrackingEnabled = true;
    this->InfoTrackingRate = 15.00f;
    this->bAddReportTimeColumn = true;
    this->bAddEngineRuntimeColumn = false;
    this->bAddTestRuntimeColumn = true;
    this->bAddCurrentMapColumn = true;
    this->bAddReportTimeAndMapColumn = false;
    this->bAddEngineRuntimeAndMapColumn = false;
    this->bAddRuntimeAndMapColumn = true;
    this->bAddPlayerLocationColumn = true;
    this->bTrackRenderTargetPoolUsage = true;
    this->bTrackAudioMemoryUsage = true;
    this->bTrackMemoryUsageInformation = true;
    this->bTrackMemoryStatInformation = true;
    this->bTrackTextureStreamingInformation = true;
    this->bTryToFilterStatErrors = true;
    this->StatsToTrack.AddDefaulted(137);
    this->bGenerateMemoryReports = false;
    this->MemoryReportCommands.AddDefaulted(1);
    this->MemoryPeakIncreaseReportThreshold = 0.75f;
    this->MemoryUtilizationReportThreshold = 0.90f;
    this->ExtraMemoryUtilizationReportAmount = 0.05f;
    this->TexturePoolUtilizationReportThreadhold = 0.75f;
    this->ExtraTexturePoolUtilizationReportAmount = 0.05f;
    this->UtilizationReportThresholdResetTime = 15.00f;
    this->TexturePoolOverBudgetReportRate = 120.00f;
    this->bInputEnabled = true;
    this->RandomInputKeyProperties.AddDefaulted(12);
    this->EquipmentProperties.AddDefaulted(8);
}

